version: "3"

services:
    bosun:
        image: sherifabdlnaby/bosun:latest
        environment:
            BOSUN_KIBANA_HOST: "kibana:5601"
            BOSUN_KIBANA_USER: "elastic"
            BOSUN_KIBANA_PASSWORD: "changeme"
            BOSUN_AUTOINDEXPATTERN_SCHEDULE: '*/5 * * * *'
            BOSUN_AUTOINDEXPATTERN_GENERALPATTERNS: '[{"pattern":"logs-apache-access-*-?","timeFieldName":"@timestamp"}]'
